### ISSUE TITLE
Error pmultiqc in ITRAQ dataset 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#81]
```
nf-core/quantms execution completed unsuccessfully!

The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)'

Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)` terminated with an error exit status (1)

Command executed:

  multiqc \
      -f \
      --config ./results/multiqc_config.yml \
       \
       \
       \
      --quantification_method feature_intensity \
      ./results \
      -o .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE":
      pmultiqc: $(multiqc --pmultiqc_version | sed -e "s/pmultiqc, version //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  No decoy peptides found -> only showing target peptides

Command error:
  |    custom_content | nf-core-quantms-summary: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-summary: Found 1 sample (html)
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'pmultiqc'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'pmultiqc'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'pmultiqc'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'pmultiqc'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Workflow Summary'.
  |           multiqc | Compressing plot data
  INFO:multiqc:Compressing plot data
  Traceback (most recent call last):
    File "/usr/local/bin/multiqc", line 10, in 
      sys.exit(run_multiqc())
    File "/usr/local/lib/python3.10/site-packages/multiqc/__main__.py", line 22, in run_multiqc
      multiqc.run_cli(prog_name="multiqc")
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/rich_click/rich_command.py", line 19, in main
      rv = super().main(*args, standalone_mode=False, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 286, in run_cli
      multiqc_run = run(**kwargs)
    File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 862, in run
      report.plot_compressed_json = report.compress_json(report.plot_data)
    File "/usr/local/lib/python3.10/site-packages/multiqc/utils/report.py", line 533, in compress_json
      json_string = json.dumps(data).encode("utf-8", "ignore").decode("utf-8")
    File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
      return _default_encoder.encode(obj)
    File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
      chunks = self.iterencode(o, _one_shot=True)
    File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
      return _iterencode(o, 0)
    File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
      raise TypeError(f'Object of type {o.__class__.__name__} '
  TypeError: Object of type int64 is not JSON serializable

Work dir:
  /hps/nobackup/juan/pride/reanalysis/differential-expression/tmt/PDC000111/work/5f/878134b2961e22d46f94944581bd28

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

**Comment by ypriverol** [comment]
Folder here: http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/878134b2961e22d46f94944581bd28/

**Comment by WangHong007** [comment]
I can't see how this happend, do you have any idea about this @daichengxin ?
