### ISSUE TITLE
Another error pmultiqc

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#82]
```
-[nf-core/quantms] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)'

Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)` terminated with an error exit status (1)

Command executed:

  multiqc \
      -f \
      --config ./results/multiqc_config.yml \
       \
       \
       \
      --quantification_method feature_intensity \
      ./results \
      -o .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE":
      pmultiqc: $(multiqc --pmultiqc_version | sed -e "s/pmultiqc, version //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  │     output = mod()                                                           │
  │   File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/qua │
  │     self.parse_out_mzTab()                                                   │
  │   File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/qua │
  │     self.cal_num_table_data[i] = {'sample_name': self.exp_design_table[i]['S │
  │ KeyError: '20HeLace.mzML'                                                    │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  DEBUG:multiqc:Oops! The 'quantms' MultiQC module broke...
  ================================================================================
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 654, in run
      output = mod()
    File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/quantms.py", line 152, in __init__
      self.parse_out_mzTab()
    File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/quantms.py", line 1407, in parse_out_mzTab
      self.cal_num_table_data[i] = {'sample_name': self.exp_design_table[i]['Sample'],
  KeyError: '20HeLace.mzML'
  ================================================================================
  |    custom_content | nf-core-quantms-methods-description: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-methods-description: Found 1 sample (html)
  |    custom_content | software_versions: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:software_versions: Found 1 sample (html)
  |    custom_content | nf-core-quantms-summary: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-summary: Found 1 sample (html)
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Methods Description'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-methods-description' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Workflow Summary'.
  |           multiqc | Compressing plot data
  INFO:multiqc:Compressing plot data
  |           multiqc | Report      : multiqc_report.html
  INFO:multiqc:Report      : multiqc_report.html
  |           multiqc | Data        : multiqc_data
  INFO:multiqc:Data        : multiqc_data
  DEBUG:multiqc:Moving data file from '/tmp/tmp3oino0gk/multiqc_data' to './multiqc_data'
  |           multiqc | Plots       : multiqc_plots
  INFO:multiqc:Plots       : multiqc_plots
  DEBUG:multiqc:Moving plots directory from '/tmp/tmp3oino0gk/multiqc_plots' to './multiqc_plots'
  |           multiqc | MultiQC complete
  INFO:multiqc:MultiQC complete

Work dir:
  /hps/nobackup/juan/pride/reanalysis/single-cell/PXD016921/work/09/e03e28db482a76a0e37ec1b7f09f2d

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details```

**Comment by ypriverol** [comment]
Folder here : http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/e03e28db482a76a0e37ec1b7f09f2d/

**Comment by jpfeuffer** [comment]
And maybe not hardcode mzml but just check the file prefix/basename.

**Comment by WangHong007** [comment]
@jpfeuffer We just apply it on mass spectrum files or all input files? And now we don't have a proper tool to process `bruker .d files` to get spectrum info, do we skip some steps when enable dia but .d?

**Comment by jpfeuffer** [comment]
You can do everything as before. Just don't assume everything will be mzml forever. Which means if you are trying to find files for matching or for lookup, just compare them by their basename.
Also for visualization or in tables, we could show "file_xyz" instead of "file_xyz.mzml".
Then it just does not matter what ending the input had.
For now we still need to convert them in most steps but we should get rid of this assumption.
